// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterAccessLister helps list ClusterAccesses.
// All objects returned here must be treated as read-only.
type ClusterAccessLister interface {
	// List lists all ClusterAccesses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterAccess, err error)
	// ClusterAccesses returns an object that can list and get ClusterAccesses.
	ClusterAccesses(namespace string) ClusterAccessNamespaceLister
	ClusterAccessListerExpansion
}

// clusterAccessLister implements the ClusterAccessLister interface.
type clusterAccessLister struct {
	indexer cache.Indexer
}

// NewClusterAccessLister returns a new ClusterAccessLister.
func NewClusterAccessLister(indexer cache.Indexer) ClusterAccessLister {
	return &clusterAccessLister{indexer: indexer}
}

// List lists all ClusterAccesses in the indexer.
func (s *clusterAccessLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterAccess, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterAccess))
	})
	return ret, err
}

// ClusterAccesses returns an object that can list and get ClusterAccesses.
func (s *clusterAccessLister) ClusterAccesses(namespace string) ClusterAccessNamespaceLister {
	return clusterAccessNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ClusterAccessNamespaceLister helps list and get ClusterAccesses.
// All objects returned here must be treated as read-only.
type ClusterAccessNamespaceLister interface {
	// List lists all ClusterAccesses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterAccess, err error)
	// Get retrieves the ClusterAccess from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterAccess, error)
	ClusterAccessNamespaceListerExpansion
}

// clusterAccessNamespaceLister implements the ClusterAccessNamespaceLister
// interface.
type clusterAccessNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ClusterAccesses in the indexer for a given namespace.
func (s clusterAccessNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterAccess, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterAccess))
	})
	return ret, err
}

// Get retrieves the ClusterAccess from the indexer for a given namespace and name.
func (s clusterAccessNamespaceLister) Get(name string) (*v1alpha1.ClusterAccess, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusteraccess"), name)
	}
	return obj.(*v1alpha1.ClusterAccess), nil
}
