// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterImportControls implements ClusterImportControlInterface
type FakeClusterImportControls struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var clusterimportcontrolsResource = schema.GroupVersionResource{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Resource: "clusterimportcontrols"}

var clusterimportcontrolsKind = schema.GroupVersionKind{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Kind: "ClusterImportControl"}

// Get takes name of the clusterImportControl, and returns the corresponding clusterImportControl object, and an error if there is any.
func (c *FakeClusterImportControls) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterImportControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterimportcontrolsResource, c.ns, name), &v1alpha1.ClusterImportControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterImportControl), err
}

// List takes label and field selectors, and returns the list of ClusterImportControls that match those selectors.
func (c *FakeClusterImportControls) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterImportControlList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterimportcontrolsResource, clusterimportcontrolsKind, c.ns, opts), &v1alpha1.ClusterImportControlList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterImportControlList{ListMeta: obj.(*v1alpha1.ClusterImportControlList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterImportControlList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterImportControls.
func (c *FakeClusterImportControls) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterimportcontrolsResource, c.ns, opts))

}

// Create takes the representation of a clusterImportControl and creates it.  Returns the server's representation of the clusterImportControl, and an error, if there is any.
func (c *FakeClusterImportControls) Create(ctx context.Context, clusterImportControl *v1alpha1.ClusterImportControl, opts v1.CreateOptions) (result *v1alpha1.ClusterImportControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterimportcontrolsResource, c.ns, clusterImportControl), &v1alpha1.ClusterImportControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterImportControl), err
}

// Update takes the representation of a clusterImportControl and updates it. Returns the server's representation of the clusterImportControl, and an error, if there is any.
func (c *FakeClusterImportControls) Update(ctx context.Context, clusterImportControl *v1alpha1.ClusterImportControl, opts v1.UpdateOptions) (result *v1alpha1.ClusterImportControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterimportcontrolsResource, c.ns, clusterImportControl), &v1alpha1.ClusterImportControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterImportControl), err
}

// Delete takes name of the clusterImportControl and deletes it. Returns an error if one occurs.
func (c *FakeClusterImportControls) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterimportcontrolsResource, c.ns, name, opts), &v1alpha1.ClusterImportControl{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterImportControls) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterimportcontrolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterImportControlList{})
	return err
}

// Patch applies the patch and returns the patched clusterImportControl.
func (c *FakeClusterImportControls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterImportControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterimportcontrolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterImportControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterImportControl), err
}
