// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterAccesses implements ClusterAccessInterface
type FakeClusterAccesses struct {
	Fake *FakeMulticlusterV1alpha1
	ns   string
}

var clusteraccessesResource = schema.GroupVersionResource{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Resource: "clusteraccesses"}

var clusteraccessesKind = schema.GroupVersionKind{Group: "multicluster.crd.antrea.io", Version: "v1alpha1", Kind: "ClusterAccess"}

// Get takes name of the clusterAccess, and returns the corresponding clusterAccess object, and an error if there is any.
func (c *FakeClusterAccesses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusteraccessesResource, c.ns, name), &v1alpha1.ClusterAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAccess), err
}

// List takes label and field selectors, and returns the list of ClusterAccesses that match those selectors.
func (c *FakeClusterAccesses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterAccessList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusteraccessesResource, clusteraccessesKind, c.ns, opts), &v1alpha1.ClusterAccessList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterAccessList{ListMeta: obj.(*v1alpha1.ClusterAccessList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterAccessList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterAccesses.
func (c *FakeClusterAccesses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusteraccessesResource, c.ns, opts))

}

// Create takes the representation of a clusterAccess and creates it.  Returns the server's representation of the clusterAccess, and an error, if there is any.
func (c *FakeClusterAccesses) Create(ctx context.Context, clusterAccess *v1alpha1.ClusterAccess, opts v1.CreateOptions) (result *v1alpha1.ClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusteraccessesResource, c.ns, clusterAccess), &v1alpha1.ClusterAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAccess), err
}

// Update takes the representation of a clusterAccess and updates it. Returns the server's representation of the clusterAccess, and an error, if there is any.
func (c *FakeClusterAccesses) Update(ctx context.Context, clusterAccess *v1alpha1.ClusterAccess, opts v1.UpdateOptions) (result *v1alpha1.ClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusteraccessesResource, c.ns, clusterAccess), &v1alpha1.ClusterAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAccess), err
}

// Delete takes name of the clusterAccess and deletes it. Returns an error if one occurs.
func (c *FakeClusterAccesses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusteraccessesResource, c.ns, name, opts), &v1alpha1.ClusterAccess{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterAccesses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusteraccessesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterAccessList{})
	return err
}

// Patch applies the patch and returns the patched clusterAccess.
func (c *FakeClusterAccesses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusteraccessesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterAccess), err
}
