apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: antrea
  name: labelidentityimport-edit-role
rules:
  - apiGroups:
      - multicluster.crd.antrea.io
    resources:
      - labelidentityimports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: antrea
  name: labelidentityimport-view-role
rules:
  - apiGroups:
      - multicluster.crd.antrea.io
    resources:
      - labelidentityimports
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: antrea
  name: labelidentityimport-leader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: labelidentityimport-edit-role
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: antrea-multicluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: antrea
  name: labelidentityimport-member-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: labelidentityimport-view-role
subjects:
  - kind: ServiceAccount
    name: member-access-sa
    namespace: antrea-multicluster