// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	scheme "antrea.io/antrea/multicluster/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterImportControlsGetter has a method to return a ClusterImportControlInterface.
// A group's client should implement this interface.
type ClusterImportControlsGetter interface {
	ClusterImportControls(namespace string) ClusterImportControlInterface
}

// ClusterImportControlInterface has methods to work with ClusterImportControl resources.
type ClusterImportControlInterface interface {
	Create(ctx context.Context, clusterImportControl *v1alpha1.ClusterImportControl, opts v1.CreateOptions) (*v1alpha1.ClusterImportControl, error)
	Update(ctx context.Context, clusterImportControl *v1alpha1.ClusterImportControl, opts v1.UpdateOptions) (*v1alpha1.ClusterImportControl, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterImportControl, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterImportControlList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterImportControl, err error)
	ClusterImportControlExpansion
}

// clusterImportControls implements ClusterImportControlInterface
type clusterImportControls struct {
	client rest.Interface
	ns     string
}

// newClusterImportControls returns a ClusterImportControls
func newClusterImportControls(c *MulticlusterV1alpha1Client, namespace string) *clusterImportControls {
	return &clusterImportControls{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterImportControl, and returns the corresponding clusterImportControl object, and an error if there is any.
func (c *clusterImportControls) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterImportControl, err error) {
	result = &v1alpha1.ClusterImportControl{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterImportControls that match those selectors.
func (c *clusterImportControls) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterImportControlList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterImportControlList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterImportControls.
func (c *clusterImportControls) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterImportControl and creates it.  Returns the server's representation of the clusterImportControl, and an error, if there is any.
func (c *clusterImportControls) Create(ctx context.Context, clusterImportControl *v1alpha1.ClusterImportControl, opts v1.CreateOptions) (result *v1alpha1.ClusterImportControl, err error) {
	result = &v1alpha1.ClusterImportControl{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterImportControl).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterImportControl and updates it. Returns the server's representation of the clusterImportControl, and an error, if there is any.
func (c *clusterImportControls) Update(ctx context.Context, clusterImportControl *v1alpha1.ClusterImportControl, opts v1.UpdateOptions) (result *v1alpha1.ClusterImportControl, err error) {
	result = &v1alpha1.ClusterImportControl{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		Name(clusterImportControl.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterImportControl).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterImportControl and deletes it. Returns an error if one occurs.
func (c *clusterImportControls) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterImportControls) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterImportControl.
func (c *clusterImportControls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterImportControl, err error) {
	result = &v1alpha1.ClusterImportControl{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterimportcontrols").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
