// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "antrea.io/antrea/multicluster/apis/multicluster/v1alpha1"
	scheme "antrea.io/antrea/multicluster/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterAccessesGetter has a method to return a ClusterAccessInterface.
// A group's client should implement this interface.
type ClusterAccessesGetter interface {
	ClusterAccesses(namespace string) ClusterAccessInterface
}

// ClusterAccessInterface has methods to work with ClusterAccess resources.
type ClusterAccessInterface interface {
	Create(ctx context.Context, clusterAccess *v1alpha1.ClusterAccess, opts v1.CreateOptions) (*v1alpha1.ClusterAccess, error)
	Update(ctx context.Context, clusterAccess *v1alpha1.ClusterAccess, opts v1.UpdateOptions) (*v1alpha1.ClusterAccess, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterAccess, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterAccessList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterAccess, err error)
	ClusterAccessExpansion
}

// clusterAccesses implements ClusterAccessInterface
type clusterAccesses struct {
	client rest.Interface
	ns     string
}

// newClusterAccesses returns a ClusterAccesses
func newClusterAccesses(c *MulticlusterV1alpha1Client, namespace string) *clusterAccesses {
	return &clusterAccesses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterAccess, and returns the corresponding clusterAccess object, and an error if there is any.
func (c *clusterAccesses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterAccess, err error) {
	result = &v1alpha1.ClusterAccess{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusteraccesses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterAccesses that match those selectors.
func (c *clusterAccesses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterAccessList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterAccessList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusteraccesses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterAccesses.
func (c *clusterAccesses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusteraccesses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterAccess and creates it.  Returns the server's representation of the clusterAccess, and an error, if there is any.
func (c *clusterAccesses) Create(ctx context.Context, clusterAccess *v1alpha1.ClusterAccess, opts v1.CreateOptions) (result *v1alpha1.ClusterAccess, err error) {
	result = &v1alpha1.ClusterAccess{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusteraccesses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterAccess).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterAccess and updates it. Returns the server's representation of the clusterAccess, and an error, if there is any.
func (c *clusterAccesses) Update(ctx context.Context, clusterAccess *v1alpha1.ClusterAccess, opts v1.UpdateOptions) (result *v1alpha1.ClusterAccess, err error) {
	result = &v1alpha1.ClusterAccess{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusteraccesses").
		Name(clusterAccess.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterAccess).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterAccess and deletes it. Returns an error if one occurs.
func (c *clusterAccesses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusteraccesses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterAccesses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusteraccesses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterAccess.
func (c *clusterAccesses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterAccess, err error) {
	result = &v1alpha1.ClusterAccess{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusteraccesses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
